### ISSUE TITLE
Crawling from scratch

### ISSUE THREAD

**Issue by masonreznov** [shashanksiripragada/pib-crawl#2]
Hello @shashanksiripragada,
First of all, thank you for sharing your code. 
I guess the pre-scraped data and models are referred to in the readme section and the `scripts` directory. If possible could you direct me with the needful steps for scraping from scratch using your codebase?

**Comment by shashanksiripragada** [comment]
Hello @masonreznov,
The crawling code can be found at [pib/tools/scrape.py](https://github.com/shashanksiripragada/pib-crawl/blob/master/pib/tools/scrape.py). This code will write the crawled articles to the database.

**Comment by masonreznov** [comment]
Thanks @shashanksiripragada
